TRAIN_LOGS_CSV = 'train_logs.csv'

MODEL_FIELD = 'model'
IMPROVEMENTS_FIELD = 'improvements'
LOSS_FIELD = 'loss'
OPTIMIZER_FIELD = 'optimizer'

DATA_AUG_FIELD = 'data_aug'

TRAIN_ITER_ID_FIELD = 'train_iter_id'
BATCH_ITER_ID_FIELD = 'batch_iter_id'

VAL_ACC_BEST_FIELD = 'val_acc_best'
VAL_ACC_LAST_FIELD = 'val_acc_last'
VAL_ACC_HIST_FIELD = 'val_acc_hist'
VAL_LOSS_BEST_FIELD = 'val_loss_best'
VAL_LOSS_LAST_FIELD = 'val_loss_last'
VAL_LOSS_HIST_FIELD = 'val_loss_hist'

SPLIT_RATIO_FIELD = 'split_ratio'
SPLIT_SEED_FIELD = 'split_seed'

HEADERS = [MODEL_FIELD, IMPROVEMENTS_FIELD, LOSS_FIELD, OPTIMIZER_FIELD, VAL_ACC_BEST_FIELD, VAL_ACC_LAST_FIELD,
           VAL_ACC_HIST_FIELD, VAL_LOSS_BEST_FIELD, VAL_LOSS_LAST_FIELD, VAL_LOSS_HIST_FIELD, DATA_AUG_FIELD,
           TRAIN_ITER_ID_FIELD, BATCH_ITER_ID_FIELD, SPLIT_RATIO_FIELD, SPLIT_SEED_FIELD]
